CREATE TABLE if not exists ILLUSTRATION(
    ID          IDENTITY PRIMARY KEY,
    NAME        VARCHAR(255) not null,
    IMAGEBYTES  BLOB not null
);

CREATE TABLE HOMILY(
    ID      IDENTITY PRIMARY KEY,
    title   VARCHAR(255) not null,
    SPOKEN_AT  DATE NOT NULL,
    speaker VARCHAR(255) not null,
    paragraphs VARCHAR(2048) ARRAY,
    COVER_ILLUSTRATION  BIGINT,
    CONSTRAINT FK_HOMILY_ILLUSTRATION FOREIGN KEY (COVER_ILLUSTRATION) REFERENCES ILLUSTRATION
);

