openapi: 3.0.3
info:
  title: Giannitsa Web App API
  description: To-Do
  contact:
    email: papp.szabolcs.bazil@gmail.com
  version: 1.0.0

tags:
  - name: homily
    description: "Homilies"

paths:
  /homily:
    post:
      tags:
        - homily
      summary: Uploads a new homily.
      description: ""
      operationId: postHomily
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HomilyUploadRequest'
      responses:
        "200":
          description: Ok
    get:
      tags:
        - homily
      summary: Retrieves every homily.
      description: "Retrieves all stored homilies."
      operationId: getAllHomilies
      responses:
        "200":
          description: "Successful retrieval of every homily"
          content:
            application/json:
              schema:
                type: object
                properties:
                  homilies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Homily'
  /homily/{homilyId}:
    get:
      tags:
        - homily
      description: "Retrieves a single homily by its id."
      operationId: getHomily
      parameters:
        - name: homilyId
          in: path
          description: The ID of the homily to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Homily'
    put:
      tags:
        - homily
      description: Updates the contents of a single homily
      operationId: updateHomily
      parameters:
        - name: homilyId
          in: path
          description: The ID of the homily to retrieve
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Homily'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Homily'
        '404':
          description: Homily not found
    delete:
      tags:
        - homily
      description: Deletes the homily denoted by the id
      operationId: deleteHomily
      parameters:
        - name: homilyId
          in: path
          description: The ID of the homily to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Homily successfully deleted.
        '404':
          description: Homily not found.

components:
  schemas:
    Homily:
      description: |
        A homily preached at a given date by a specified speaker, containing
        the paragraphs of the spoken text as well as an optional cover
        illustration.
      type: object
      properties:
        id:
          description: |
            The unique identifier of this homily stored as a 64-bit number.
          type: integer
          format: int64
          example: 1
        title:
          description: |
            The title of the homily. Should be unique, as to differentiate
            multiple homilies preached for the same occasion.
          type: string
          example: 'The Prodigal Son 2 - Electric Boogaloo'
        date:
          description: |
            The date on which this homily was given.
          type: string
          format: date
          example: '2022-01-01'
        speaker:
          description: |
            The person who gave this homily
          type: string # TODO: define Speaker type
          example: 'Fr John'
        paragraphs:
          description: |
            The paragraphs of the homily's text in sequential order.
          type: array
          items:
            type: string
          example:
            - "First paragraph."
            - "Second paragraph."
        coverIllustration:
          description: |
            An image to render as the cover illustration of this homily.
          type: string
          format: binary
      required:
        - title
        - date
        - speaker
        - paragraphs
    HomilyUploadRequest:
      type: object
      required: [homily]
      properties:
        homily:
          $ref: '#/components/schemas/Homily'
        content:
          type: string
          format: binary
    ServiceType:
      description: |
        Enumeration of the possible service types.
      type: string
      enum:
        - matins
        - divine-liturgy
        - vespers
        - presanctified
        - paraklis
        - mnimosino
    Service:
      type: object
      properties:
        startTime:
          type: string
          format: time
        serviceType:
          $ref: '#/components/schemas/ServiceType'
    ServiceDay:
      type: object
      properties:
        issue:
          type: string
          format: date
        feast:
          type: string
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
    ServiceSchedule:
      type: object
      properties:
        validFrom:
          description: |
            The first day when this service schedule is in effect.
          type: string
          format: date
          example: '2022-01-01'
        validTill:
          description: |
            The last day when this service schedule is in effect.
          type: string
          format: date
          example: '2022-01-31'
        serviceDays:
          type: array
          items:
            $ref: '#/components/schemas/ServiceDay'