/**
 * Giannitsa Web App API
 * To-Do
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: papp.szabolcs.bazil@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A homily preached at a given date by a specified speaker, containing the paragraphs of the spoken text as well as an optional cover illustration. 
 */
export interface Homily { 
    /**
     * The unique identifier of this homily stored as a 64-bit number. 
     */
    id?: number;
    /**
     * The title of the homily. Should be unique, as to differentiate multiple homilies preached for the same occasion. 
     */
    title: string;
    /**
     * The date on which this homily was given. 
     */
    date: string;
    /**
     * The person who gave this homily 
     */
    speaker: string;
    /**
     * The paragraphs of the homily\'s text in sequential order. 
     */
    paragraphs: Array<string>;
    /**
     * An image to render as the cover illustration of this homily. 
     */
    coverIllustration?: Blob;
}

