/**
 * Giannitsa Web App API
 * To-Do
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: papp.szabolcs.bazil@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration of the possible service types. 
 */
export type ServiceType = 'matins' | 'divine-liturgy' | 'vespers' | 'presanctified' | 'paraklis' | 'mnimosino';

export const ServiceType = {
    Matins: 'matins' as ServiceType,
    DivineLiturgy: 'divine-liturgy' as ServiceType,
    Vespers: 'vespers' as ServiceType,
    Presanctified: 'presanctified' as ServiceType,
    Paraklis: 'paraklis' as ServiceType,
    Mnimosino: 'mnimosino' as ServiceType
};

