/**
 * Giannitsa Web App API
 * To-Do
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: papp.szabolcs.bazil@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceDay } from './serviceDay';


export interface ServiceSchedule { 
    /**
     * The first day when this service schedule is in effect. 
     */
    validFrom?: string;
    /**
     * The last day when this service schedule is in effect. 
     */
    validTill?: string;
    serviceDays?: Array<ServiceDay>;
}

