/**
 * Giannitsa Web App API
 * To-Do
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: papp.szabolcs.bazil@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceType } from './serviceType';


export interface Service { 
    startTime?: string;
    serviceType?: ServiceType;
}

